export const legacyEmeaPlayers = [
    { slug: "adidas-germany", name: " Adidas" },
    { slug: "ah-netherlands", name: " Albert Heijn" },
    { slug: "allegro-poland", name: "Allegro" },
    { slug: "amazon-uk", name: " Amazon UK" },
    { slug: "asos-uk", name: " Asos" },
    { slug: "auchan-france", name: " Auchan" },
    { slug: "b-and-q-uk", name: " B&Q" },
    { slug: "bol-netherlands", name: " Bol" },
    { slug: "calzedonia-italy", name: " Calzedonia" },
    { slug: "carrefour-france", name: " Carrefour" },
    { slug: "chronodrive-france", name: " Chronodrive" },
    { slug: "continente-portugal", name: " Continente" },
    { slug: "coop-switzerland", name: " Coop" },
    { slug: "costa-del-mar-italy", name: " Costa del Mar" },
    { slug: "decathlon-france", name: " Decathlon" },
    { slug: "delhaize-belgium", name: " Delhaize" },
    { slug: "delio-poland", name: " Delio" },
    { slug: "dior-france", name: " Dior" },
    { slug: "e-leclerc-france", name: "e-leclerc-france" },
    { slug: "edeka-germany", name: " Edeka" },
    { slug: "galaxus-switzerland", name: " Galaxus" },
    { slug: "gucci-france", name: " Gucci" },
    { slug: "hm-de-de-sweden", name: " H&M DE" },
    { slug: "ikea-de-de-sweden", name: " Ikea" },
    { slug: "interdiscount-switzerland", name: " Interdiscount" },
    { slug: "jdsports-uk", name: " JD Sports" },
    { slug: "johnlewis-uk", name: " John Lewis" },
    { slug: "jumbo-switzerland", name: " Jumbo" },
    { slug: "kiehls-france", name: "Kiehl's" },
    { slug: "knuspr-germany", name: " Knuspr" },
    { slug: "laredoute-france", name: " La Redoute" },
    { slug: "leclercdrive-france", name: " Leclerc Drive" },
    { slug: "lego-denmark", name: " Lego" },
    { slug: "leroymerlin-france", name: " Leroy Merlin" },
    { slug: "lidl-germany", name: " Lidl" },
    { slug: "louisvuitton-france", name: " Louis Vuitton" },
    { slug: "marksandspencer-uk", name: " Marks & Spencer" },
    { slug: "mediamarkt-germany", name: " Media Markt" },
    { slug: "metro-germany", name: " Metro" },
    { slug: "migros-switzerland", name: " Migros" },
    { slug: "next-uk", name: " Next UK" },
    { slug: "noon-uae", name: " Noon" },
    { slug: "ocado-uk", name: " Ocado" },
    { slug: "otto-germany", name: " Otto" },
    { slug: "puma-germany", name: " Puma" },
    { slug: "ray-ban-italy", name: " Ray-Ban" },
    { slug: "rewe-germany", name: " Rewe" },
    { slug: "sephora-france", name: " Sephora" },
    { slug: "shein-uk", name: " Shein UK" },
    { slug: "sportsdirect-uk", name: " Sports Direct" },
    { slug: "tesco-uk", name: " Tesco" },
    { slug: "tezenis-italy", name: " Tezenis" },
    { slug: "thuisbezorgd-netherlands", name: " Thuisbezorgd" },
    { slug: "ysl-france", name: " Saint Laurent" },
    { slug: "zalando-germany", name: " Zalando" },
    { slug: "zara-spain", name: " Zara" },

    {
        name: "01. Albert Einstein (hospital)",
        slug: "einstein-hospital",
    },
    {
        name: "02. Sírio Libanês",
        slug: "sirio-libanes",
    },
    {
        name: "03. Rede D_or",
        slug: "rede-dor",
    },
    {
        name: "04. Dasa (9 de julho)",
        slug: "nove-de-julho",
    },
    {
        name: "05. Mater Dei",
        slug: "materdei",
    },
    {
        name: "06. Dasa (Delboni)",
        slug: "dasa",
    },
    {
        name: "07. Fleury",
        slug: "fleury",
    },
    {
        name: "08. Sabin",
        slug: "sabin",
    },
    {
        name: "09. Albert Einstein (laboratório)",
        slug: "einstein-lab",
    },
    {
        name: "10. Hapvida",
        slug: "hapvida",
    },
    {
        name: "11. SulAmérica",
        slug: "sulamerica",
    },
    {
        name: "12. Amil",
        slug: "amil",
    },
    {
        name: "13. Unimed Nacional",
        slug: "unimed",
    },
    {
        name: "14. Sami",
        slug: "sami",
    },
    {
        name: "15. Porto Saúde",
        slug: "porto-saude",
    },
    {
        name: "16. Prevent Senior",
        slug: "prevent-senior",
    },

    { name: "Actinver", slug: "actinver" },
    { name: "Afirme", slug: "afirme" },
    { name: "Banamex", slug: "banamex" },
    { name: "Banco Azteca", slug: "banco-azteca" },
    { name: "Banco Compartamos", slug: "banco-compartamos" },
    { name: "Banco de Bogotá", slug: "banco-de-bogota" },
    { name: "Banco de Chile", slug: "banco-de-chile" },
    { name: "Banco Estado", slug: "banco-estado" },
    { name: "Banco Macro", slug: "banco-macro" },
    { name: "Banco Popular", slug: "banco-popular" },
    { name: "Banco Security", slug: "banco-security" },
    { name: "Bancolombia", slug: "bancolombia" },
    { name: "BanCoppel", slug: "bancoppel" },
    { name: "Banorte", slug: "banorte" },
    { name: "BCI", slug: "bci" },
    { name: "CIBANCO", slug: "cibanco" },
    { name: "Davivienda", slug: "davivienda" },
    { name: "Invex", slug: "invex" },
    { name: "Mercado Pago", slug: "mercado-pago" },
    { name: "Mifel", slug: "mifel" },
    { name: "Monex", slug: "monex" },
    { name: "Naranja X", slug: "naranja-x" },
    { name: "NuBank", slug: "nubank" },
    { name: "Santander", slug: "santander" },
    { name: "Uala", slug: "uala" },
];
